/**
 * makePlaceholderCard.js — branded placeholder artwork for a project.
 *
 * Project thumbnails render at 400x160 with `object-cover`, so a square logo
 * gets cropped to a 2.5:1 strip and its lettering sliced in half. A placeholder
 * has to be built at the aspect ratio it will be shown at, or it reads as a
 * broken image rather than a deliberate one.
 *
 * Output is an SVG rather than a raster: it is a few hundred bytes, stays sharp
 * at any density, and needs no build step. Colours are fixed rather than
 * theme-reactive — the card sits on its own tinted panel in both themes, and an
 * image that changed with the theme would be the only one on the page that did.
 *
 * Usage:
 *   node scripts/makePlaceholderCard.js --out public/x-card.svg \
 *        --title "PeakRoutine" --subtitle "AI Health & Wellness Platform"
 */
import { writeFileSync } from 'node:fs';

const WIDTH = 1200;
const HEIGHT = 480;

/** SVG text is XML: an unescaped & or < in a project title breaks the file. */
const esc = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/**
 * Break a title across lines so a long one does not overflow the card. Rough
 * per-character width is fine here — the text is centred and the box is wide.
 */
export function wrapTitle(title, maxChars = 22) {
  const words = String(title).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';
  for (const w of words) {
    if (line && `${line} ${w}`.length > maxChars) {
      lines.push(line);
      line = w;
    } else {
      line = line ? `${line} ${w}` : w;
    }
  }
  if (line) lines.push(line);
  return lines.slice(0, 3);
}

export function renderCard({ title, subtitle = '', accent = '#2dd4bf' }) {
  const lines = wrapTitle(title);
  const titleSize = lines.length > 2 ? 96 : 116;
  const blockHeight = lines.length * titleSize * 1.08 + (subtitle ? 64 : 0);
  let y = HEIGHT / 2 - blockHeight / 2 + titleSize * 0.82;

  const titleSpans = lines
    .map((l) => {
      const span = `<text x="${WIDTH / 2}" y="${Math.round(y)}" text-anchor="middle" font-size="${titleSize}" font-weight="700" fill="#f1f5f9">${esc(l)}</text>`;
      y += titleSize * 1.08;
      return span;
    })
    .join('\n  ');

  const sub = subtitle
    ? `\n  <text x="${WIDTH / 2}" y="${Math.round(y + 26)}" text-anchor="middle" font-size="40" font-weight="500" fill="${accent}" letter-spacing="1.5">${esc(subtitle)}</text>`
    : '';

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" width="${WIDTH}" height="${HEIGHT}" role="img" aria-label="${esc(title)}">
  <title>${esc(title)}</title>
  <!-- PLACEHOLDER ARTWORK. Generated by scripts/makePlaceholderCard.js.
       Replace with a real screenshot when one exists. -->
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#0b1220"/>
      <stop offset="1" stop-color="#0f2a2b"/>
    </linearGradient>
    <pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse">
      <path d="M48 0H0V48" fill="none" stroke="${accent}" stroke-opacity="0.07" stroke-width="1"/>
    </pattern>
  </defs>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#bg)"/>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#grid)"/>
  <rect x="0" y="0" width="${WIDTH}" height="6" fill="${accent}" opacity="0.85"/>
  <g font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif">
  ${titleSpans}${sub}
  </g>
</svg>
`;
}

function main() {
  const args = process.argv.slice(2);
  const get = (flag) => {
    const i = args.indexOf(flag);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const out = get('--out');
  const title = get('--title');
  if (!out || !title) {
    console.error('Usage: --out <file.svg> --title <title> [--subtitle <text>]');
    process.exit(2);
  }
  writeFileSync(out, renderCard({ title, subtitle: get('--subtitle') || '' }));
  console.log(`Wrote ${out}`);
}

if (process.argv[1] && process.argv[1].endsWith('makePlaceholderCard.js')) main();
