/**
 * serviceWorker.js — generate `dist/sw.js` from the real build output.
 *
 * WHY GENERATED AND NOT HAND-WRITTEN
 * ──────────────────────────────────
 * A precache list has to name the hashed filenames the build actually
 * produced. Written by hand it goes stale on the next build and the worker
 * precaches URLs that 404, which fails the whole install and leaves visitors
 * with no offline support and no error anyone will see.
 *
 * UPDATE SAFETY — the part worth reading before changing anything
 * ──────────────────────────────────────────────────────────────
 * A service worker that serves stale code is the worst bug in this repo's
 * surface area, because the fix is also cached. Three deliberate choices keep
 * that from happening:
 *
 *   1. NO `skipWaiting`, NO `clients.claim`. A new worker waits until every
 *      tab using the old one has gone. That matters because a page loaded
 *      with the old HTML is still asking for the old chunk names; taking over
 *      mid-session and dropping the old cache would break the page under the
 *      reader's hands.
 *   2. Old caches are deleted only in `activate`, which by (1) runs when no
 *      old client is left.
 *   3. Navigations are NETWORK-FIRST. HTML is the thing that names the asset
 *      hashes, so a stale HTML pins a visitor to a stale build forever. Cache
 *      is the fallback for offline, never the default.
 *
 * Hashed assets are cache-first because their names change when the content
 * changes — that is what the hash is for.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

/**
 * Files fetched and stored the moment the worker installs.
 *
 * Deliberately just the SHELL: every route's HTML, the font, and the assets
 * `index.html` itself references. Everything else — the lazy section chunk,
 * the chat chunk, images — is cached at runtime as it is actually used, by
 * the cache-first rule for `/assets/`.
 *
 * The first version matched asset names with a regex, which is how it ended up
 * precaching a 482 KB lazy chunk: Vite emits more than one file starting
 * `index-`, and only one of them is the entry. Reading the real reference list
 * out of the HTML cannot make that mistake, and it stays correct as chunking
 * changes. It is the same parse `checkBundleSize.js` uses to define the
 * initial payload, for the same reason.
 *
 * Precaching the whole build would make the site fully usable on a first-ever
 * offline visit, which nobody has, at the cost of roughly doubling the bytes
 * for a visitor who reads one page and leaves. Runtime caching covers the case
 * that actually happens: visited before, offline now.
 */
function precacheList(outDir) {
  const html = readFileSync(join(outDir, 'index.html'), 'utf8');
  const eager = new Set(
    [...html.matchAll(/(?:src|href)="(\/assets\/[^"]+)"/g)].map((m) => m[1]),
  );

  const files = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else files.push(`/${relative(outDir, full).split(/[\\/]/).join('/')}`);
    }
  };
  walk(outDir);

  return files.filter(
    (f) =>
      // Every route's HTML, so a shared link opens offline rather than 404ing
      // into the worker's fallback.
      f.endsWith('.html') ||
      // Stable, small, and needed before text renders in the right face.
      f.startsWith('/fonts/') ||
      eager.has(f),
  );
}

function renderWorker(precache, version) {
  return `/* Generated by scripts/serviceWorker.js — do not edit. Built ${version}. */
const VERSION = ${JSON.stringify(version)};
const CACHE = 'hr-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  // No skipWaiting: this worker waits until every tab on the old one is gone.
  // A page loaded with the previous HTML is still requesting the previous
  // chunk names, and taking over would pull them out from under it.
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // addAll is atomic — one 404 fails the whole install. Add individually so
      // a single missing asset cannot leave the visitor with no worker at all.
      Promise.all(PRECACHE.map((url) => cache.add(url).catch(() => {}))),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k.startsWith('hr-') && k !== CACHE).map((k) => caches.delete(k))),
    ),
  );
});

/** Cache-first: for content-hashed URLs, a hit is by definition still correct. */
async function cacheFirst(request) {
  const hit = await caches.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(CACHE);
    cache.put(request, response.clone());
  }
  return response;
}

/**
 * Network-first, cache as fallback. Used for navigations: HTML names the asset
 * hashes, so serving it from cache by default would pin a visitor to an old
 * build indefinitely.
 */
async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE);
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    const hit = (await caches.match(request)) || (await caches.match('/index.html'));
    if (hit) return hit;
    throw err;
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // The API is never cached. Answers depend on the request and on rate-limit
  // state, and a cached one would be wrong in a way nobody could see.
  if (url.pathname.startsWith('/api/')) return;

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
    return;
  }

  if (url.pathname.startsWith('/assets/') || url.pathname.startsWith('/fonts/')) {
    event.respondWith(cacheFirst(request));
  }
});
`;
}

/** @returns {import('vite').Plugin} */
export function serviceWorkerPlugin() {
  let outDir = '';
  return {
    name: 'service-worker',
    apply: 'build',
    configResolved(config) {
      outDir = resolve(config.root, config.build.outDir);
    },
    // `closeBundle` runs after the HTML generators, so the route files exist.
    closeBundle() {
      if (!existsSync(join(outDir, 'index.html'))) return;
      const precache = precacheList(outDir);
      // The version is derived from the precached CONTENT, so an identical
      // rebuild does not churn every visitor's cache, and a real change does.
      const version = createHash('sha256')
        .update(precache.map((f) => `${f}:${statSync(join(outDir, `.${f}`)).size}`).join('\n'))
        .digest('hex')
        .slice(0, 12);
      writeFileSync(join(outDir, 'sw.js'), renderWorker(precache, version));
    },
  };
}

export { precacheList, renderWorker };
